spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
  jpa:
   hibernate:
    ddl-auto: update

    
  application:
    name: product-service
    
server:
 port: 5555