eureka:
 client:
  register-with-eureka: true
  fetch-registry: false
  service-url:
   defaultZone: http://localhost:8761/eureka
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
  jpa:
   hibernate:
    ddl-auto: update
  application:
    name: coupon-service
    

  

    
 