spring:
  config:
   location: http://localhost:8888/
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
  jpa:
   hibernate:
    ddl-auto: update

    
  application:
    name: product-service
 
    

    
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      

  
resilience4j:
  retry:
    instances:
     product-api:
      max-attempts: 2
      wait-duration: 3s
      
      
    